### ISSUE TITLE
gitops operator auto removing secret for in-cluster argocd instance

### ISSUE THREAD

**Issue by joyartoun** [redhat-developer/gitops-operator#255] opened 2021-12-20 08:28 UTC
Hi team,

I am trying to create Application sets, mostly working, but when I am trying to use the cluster generator (with labeling the secrets) it's not really working as intended. 

I am following this example https://argocd-applicationset.readthedocs.io/en/stable/Generators-Cluster/#cluster-generator however this only works if you have a secret defined for the cluster you want to manage. The in-cluster cluster that comes default does not have a secret defined. To fix that, you are supposed to follow this solution https://argocd-applicationset.readthedocs.io/en/stable/Generators-Cluster/#deploying-to-the-local-cluster. That works for maybe 5 minutes, but it seems that something removes the secret. I have not located what removes the secret, but my guess is the gitops-operator-controller-manager in the openshift-operators namespace. 

Are you aware of this? Do you maybe have a workaround for this problem?
This is causing us to not be able to use the cluster generator with openshift-gitops.

Best regards

**Comment by joyartoun** [comment] 2022-01-09 22:15
No comment on this at all?
This renders the cluster generator rather userless

**Comment by morningspace** [comment] 2022-02-01 15:51
I see the same issue. I guess some operator, maybe the gitops operator, did this.

**Comment by iam-veeramalla** [comment] 2022-02-01 17:14
@morningspace this issue is fixed in the latest versions. What is the version of operator that you are using ?

**Comment by morningspace** [comment] 2022-02-01 21:56
Hi @iam-veeramalla thanks for your prompt reply. I'm using OCP 4.8.27, and install the OpenShift GitOps via Operator Hub, and it's based on Argo CD 2.2.2. Any idea how I can get the fix?

**Comment by iam-veeramalla** [comment] 2022-02-02 18:57
Hi @bluengo @varshab1210 @rjeczkow  is this something that we are aware of ? please let me know if we can mark this as a bug ? Thanks

**Comment by varshab1210** [comment] 2022-02-03 07:25
Hi @joyartoun @morningspace . Could you please provide us with more details so that we can try to reproduce this issue from our end? Thanks

**Comment by morningspace** [comment] 2022-02-03 10:07
@varshab1210 It's easy to reproduce. Just follow the steps here: https://github.com/argoproj/applicationset/issues/35#issuecomment-769358837, you will see the secret for in-cluster created in openshift-gitops namespace, then wait for a few minutes, the secret disappeared.

**Comment by rjeczkow** [comment] 2022-02-03 14:36
hi @morningspace. We're not able to reproduce the issue following https://argocd-applicationset.readthedocs.io/en/stable/Generators-Cluster/#deploying-to-the-local-cluster. The cluster-<server_name> secret gets created in openshift-gitops namespace after the cluster name change in argocd UI and it persists. It was verified on OCP 4.8 and 4.9.

Please watch the events after the cluster name change in argocd with `oc get events -n openshift-gitops -w` to see what specifically is deleting the secret. Thanks

**Comment by morningspace** [comment] 2022-02-03 20:36
Thanks @rjeczkow, may I know which version of OpenShift GitOps (and Argo CD) you use, also OCP including the minor version.

**Comment by varshab1210** [comment] 2022-02-04 05:34
Hi @morningspace, we used GitOps v1.4.1 which uses Argo CD v2.2.2 on OCP 4.8.27

**Comment by morningspace** [comment] 2022-02-04 08:11
Interestingly, I am using exactly the same versions. I will double check how can reproduce it then get back to you. Thanks!

**Comment by joyartoun** [comment] 2022-02-04 13:21
Hi, 

I just tried this in a cluster with openshift version 4.9.5, gitops-operator version 1.4.1 which in turn has argocd chart version of 3.0.1 which seems to be argocd v2.2.2 

I edit the cluster inside the argocd application, change the name of the cluster and the secret gets created. After approximately 5-10 mins it gets deleted.

**Comment by varshab1210** [comment] 2022-02-04 15:47
Hi @joyartoun,

We could not reproduce the issue in OCP 4.9.5 as well. The secret that was created in `openshift-gitops` namespace after changing the name of the cluster, persisted for more than an hour now and we do not see a problem.

Please check with `oc get events -n openshift-gitops -w` to get more details on how the secret is getting deleted in your environment. Thanks.

OCP version: 4.9.5
GitOps operator version: 1.4.1 (Argo CD v2.2.2)

**Comment by joyartoun** [comment] 2022-02-04 19:07
Hi @varshab1210, nothing shows upp If I check events, it took approximately 30 minutes until the secret got deleted, but as I mentioned, nothing in the events in the openshift-gitops namespace

**Comment by joyartoun** [comment] 2022-02-08 08:17
Hi, 

I just tried to create a new cluster which is running openshift 4.9.12 and openshift gitops 1.4.1, almost one hour and the secret is not deleted. 

Information about the cluster which it is not working: 
openshift-version 4.9.5
openshift-gitops 1.4.1

Following exactly this guide https://argocd-applicationset.readthedocs.io/en/stable/Generators-Cluster/#deploying-to-the-local-cluster

Only difference I can think of is that in the cluster which it is not working, I am using my own user which is a cluster-admin in openshift to log in to the argoCD UI, in the cluster where it is working I am using the admin user which is installed with openshift-gitops. Could that maybe be the problem here?

**Comment by joyartoun** [comment] 2022-02-08 09:38
Hi again,

I wrote too soon, even with the complete new installed cluster and installed openshift-gitops operator, the secret gets deleted. 
What I did:
1. install openshift 4.9.12
2. Install openshift-gitops operator from operatorhub
3. Log in to argocd with admin user and password from the secret openshift-gitops-cluster
4. In ArgoCD, go to settings -> Clusters -> https://kubernetes.default.svc
5. Edit the cluster, change the name
6. Secret gets created
7. Wait up to an hour, secret gets deleted, nothing in events showing, nothing in the operator logs

The only log I see that is remotely referencing this secret is this log in the openshift-gitops-applicationset-controller pod
`
time="2022-02-08T09:18:59Z" level=info msg="processing event for cluster secret" name=cluster-kubernetes.default.svc-3396314289 namespace=openshift-gitops type=createSecretEventHandler

time="2022-02-08T09:18:59Z" level=info msg="listed ApplicationSets" count=0 type=createSecretEventHandler

time="2022-02-08T09:26:34Z" level=info msg="Alloc=6733 TotalAlloc=26715 Sys=73553 NumGC=71 Goroutines=49"

time="2022-02-08T09:34:39Z" level=info msg="processing event for cluster secret" name=cluster-kubernetes.default.svc-3396314289 namespace=openshift-gitops type=createSecretEventHandler`

At the ltime of the ast message, the secret got deleted

**Comment by bluengo** [comment] 2022-02-09 10:38
Thank you very much for providing the info, @joyartoun! 

Let us give it a try again, we'll keep you up to date.

**Comment by bluengo** [comment] 2022-02-09 17:37
Hi @joyartoun. We have reproduced the same steps in two OpenShift 4.9.12 clusters (one in AWS, the other in GCP) and waited up to two hours in each case. The secret was still in there (image below) and neither the logs from the pods nor the events in the _openshift-gitops_ namespace, show anything remarkable.

![screenshot-kubectl-get-secret](https://user-images.githubusercontent.com/88427171/153255397-c8d8487e-a7f1-401e-8461-2b4cf36056e3.png)

In the logs of _openshift-gitops-applicationset-controller_ we can see similar messages as well:
```
time="2022-02-09T15:00:24Z" level=info msg="processing event for cluster secret" name=cluster-kubernetes.default.svc-3396314289 namespace=openshift-gitops type=createSecretEventHandler
time="2022-02-09T15:00:24Z" level=info msg="listed ApplicationSets" count=0 type=createSecretEventHandler
time="2022-02-09T15:03:53Z" level=info msg="Alloc=6985 TotalAlloc=26239 Sys=73297 NumGC=10 Goroutines=49"
time="2022-02-09T15:13:53Z" level=info msg="Alloc=6967 TotalAlloc=26395 Sys=73297 NumGC=15 Goroutines=49"
(...)
```

At this point, I would recommend opening a support case and diving more deeply into your environment, to be able to gather all the needed information to understand which component is causing this issue.

I apologize for the inconvenience. Let us know if we can provide further help.

**Comment by joyartoun** [comment] 2022-02-09 19:04
Hi @bluengo, thank you very much for testing this. When you say open a support case, you mean with the redhat support correct?

Another question, is there a way of enabling debug on the operator or the controllers? maybe there is something hidden in the debug logs.

**Comment by bluengo** [comment] 2022-02-11 11:03
Hello @joyartoun. Sorry for the delay.
Yes, I was referring to the RedHat support service. A deeper context will be needed to understand this issue.
You can try to enable [audit log policy](https://docs.openshift.com/container-platform/4.9/security/audit-log-policy-config.html) for the API server, so you can capture the `delete` verb when the secret is deleted by viewing the [audit logs](https://docs.openshift.com/container-platform/4.9/security/audit-log-view.html). That may lead you to the root event for this deletion.

In this example, you can see how a task from openshift-pipelines operator deletes the secret:
```
{"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"Metadata","auditID":"f06fa728-1e43-48c0-81f4-03c6da13bd9f","stage":"ResponseComplete","requestURI":"/apis/image.openshift.io/v1/namespaces/openshift-gitops/secrets/","verb":"delete","name":"cluster-kubernetes.default.svc-3396314289","user":{"username":"system:serviceaccount:openshift-pipelines-operator:pipelines-operator","groups":["system:serviceaccounts","system:serviceaccounts:openshift-pipelines-operator","system:authenticated"],"extra":{"authentication.kubernetes.io/pod-name":["pipelines-operator-task-6fd89bb96c-zlbng"],"authentication.kubernetes.io/pod-uid":["1997dcc8-c34b-40ed-8756-339231b472c7"]}} (...)
```

**Comment by joyartoun** [comment] 2022-02-14 10:14
Hi @bluengo thanks for the tip. 

Just wanted to show my findings, haven't opened a ticket with RedHat support yet.

The secret named cluster-kubernetes.default.svc-3396314289 got created at 14:34:16 by the service account system:serviceaccount:openshift-gitops:openshift-gitops-argocd-server and by pod openshift-gitops-server in the openshift-gitops namespace. 

The secret cluster-kubernetes.default.svc-3396314289 got deleted at 14:48:37 by the service account system:serviceaccount:openshift-operators:gitops-operator-controller-manager and the pod gitops-operator-controller-manager in the openshift-gitops namespace.
![create](https://user-images.githubusercontent.com/29835230/153844637-e65df401-e803-4478-9d4f-a1639e72270d.png)
![delete](https://user-images.githubusercontent.com/29835230/153844652-4b14adb6-bfdd-4bcb-b869-79f4f5b3180e.png)

**Comment by tjungbauer** [comment] 2022-03-19 04:24
Hello, I have the exact same issue: the secrets gets deleted after some time (seems an hours or 2). 

I am using OpenShift 4.10, ArgoCD 2.2.5, openshift-gitops 1.4.3

**Comment by iam-veeramalla** [comment] 2022-05-13 09:48
[GITOPS-2015](https://issues.redhat.com/browse/GITOPS-2015) is the JIRA for Internal tracking.

**Comment by wtam2018** [comment] 2022-05-19 20:26
Fixed in the upstream https://github.com/argoproj-labs/argocd-operator/pull/588

**Closed by wtam2018** 2022-05-19 20:26 UTC
Labels: triage:required, jira-created
