### ISSUE TITLE
Description field is removed from argoproj.v1alpha1.AppProject.spec.roles

### ISSUE THREAD

**Issue by lsteck** [redhat-developer/gitops-operator#270] opened 2022-01-26 18:34 UTC
**Describe the bug**
Using Argo CD v2.2.2 that is installed via Red Hat OpenShift GitOps v1.4.0.   

Syncing an AppProject with a role description fails with error
`
error validating data: ValidationError(AppProject.spec.roles[0]): unknown field "description" in io.argoproj.v1alpha1.AppProject.spec.roles
`

Example resource
```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
spec:
  roles:
  - name: read-only
    description: Read-only privileges to my-project
```
This is a valid property defined here
https://github.com/argoproj/argo-cd/blob/0aeda4366d107ac14b2fe9ad3a3163a18190c942/manifests/crds/appproject-crd.yaml#L162-L171

But that property is not in the CRD that is loaded in the cluster.  
<img width="969" alt="argoproj v1alpha1 AppProject" src="https://user-images.githubusercontent.com/3800155/151223226-195738c4-57b2-4eb6-a790-9bd838ac2f9e.png">

I've tested this on both OCP 4.7 and 4.8.

**To Reproduce**
1. Install Red Hat OpenShift GitOps v1.4.0
2. Try to deploy an AppProject with a spec.roles.description. It will fail
3. View the AppProject CRD in the cluster and you can see the "description" property does not exists on "roles"

**Expected behavior**
Description is a valid property so the AppProject should sync successfully

**Screenshots**
<img width="1312" alt="argo-sync-error" src="https://user-images.githubusercontent.com/3800155/151224434-1226b41b-375a-477f-87e4-998dc454269e.png">

**Comment by iam-veeramalla** [comment] 2022-01-26 19:04
Hi @lsteck , Let me tell you that we are aware of the issue and we have fixed it as part of v1.4.1 which should be available very soon(EOB today).

**Comment by iam-veeramalla** [comment] 2022-01-26 19:05
Looks like v1.4.1 is out. @lsteck please give it a try.

**Comment by hollisc** [comment] 2022-01-26 19:11
Thanks for the quick update.  I verified that its been fixed in the 1.4.1 version of the operator

**Comment by csantanapr** [comment] 2022-01-26 19:14
Thanks for the quick update. Is the problem only present on `v1.4.0` and not previous versions?

**Comment by iam-veeramalla** [comment] 2022-01-26 19:14
@lsteck closing the issue as per the confirmation from @hollisc. Please feel free to re-open if you still see the issue after upgrade.

**Comment by iam-veeramalla** [comment] 2022-01-26 19:15
> Thanks for the quick update. Is the problem only present on `v1.4.0` and not previous versions?

Yes. The issue is only with the version 1.4.0

**Closed by iam-veeramalla** 2022-01-26 19:14 UTC
Labels: kind/bug, fixed-in-latest

**Comment by lsteck** [comment] 2022-01-26 19:22
Yep, verified it fixed my problem as well.  Thanks!
