### ISSUE TITLE
Pods keep being recreated

### ISSUE THREAD

**Issue by davidkarlsen** [redhat-developer/gitops-operator#242] opened 2021-10-18 00:00 UTC
**Describe the bug**
After upgrading the operator to 1.3.0 

pods keep being recreated:
```
k -n jfr-argocd get pods
NAME                                  READY   STATUS              RESTARTS   AGE
argocd-application-controller-0       1/1     Running             0          10s
argocd-dex-server-584b55c5d8-qfwgt    1/1     Running             0          35m
argocd-redis-dd8475b8-tc69l           1/1     Running             0          35m
argocd-repo-server-794db5957d-26thj   0/1     ContainerCreating   0          2s
argocd-repo-server-949677768-kqtsg    1/1     Running             0          101s
argocd-server-69c56dd7c6-hgbn7        0/1     Terminating         0          8s
argocd-server-6b6846dc74-fq99z        1/1     Running             0          3m20s
```

```
177m        Normal    SuccessfulCreate    replicaset/argocd-server-7698f7ddb4         Created pod: argocd-server-7698f7ddb4-dhj2k
177m        Normal    SuccessfulDelete    replicaset/argocd-server-7698f7ddb4         Deleted pod: argocd-server-7698f7ddb4-dhj2k
177m        Normal    SuccessfulCreate    replicaset/argocd-server-7698f7ddb4         Created pod: argocd-server-7698f7ddb4-k7cbm
176m        Normal    SuccessfulDelete    replicaset/argocd-server-7698f7ddb4         Deleted pod: argocd-server-7698f7ddb4-k7cbm
176m        Normal    SuccessfulCreate    replicaset/argocd-server-7698f7ddb4         Created pod: argocd-server-7698f7ddb4-2hzfn
176m        Normal    SuccessfulDelete    replicaset/argocd-server-7698f7ddb4         Deleted pod: argocd-server-7698f7ddb4-2hzfn
39m         Normal    SuccessfulCreate    replicaset/argocd-server-7698f7ddb4         Created pod: argocd-server-7698f7ddb4-ccxbh
39m         Normal    SuccessfulDelete    replicaset/argocd-server-7698f7ddb4         Deleted pod: argocd-server-7698f7ddb4-ccxbh
39m         Normal    SuccessfulCreate    replicaset/argocd-server-7698f7ddb4         Created pod: argocd-server-7698f7ddb4-pj47w
39m         Normal    SuccessfulDelete    replicaset/argocd-server-7698f7ddb4         Deleted pod: argocd-server-7698f7ddb4-pj47w
38m         Normal    SuccessfulCreate    replicaset/argocd-server-7698f7ddb4         Created pod: argocd-server-7698f7ddb4-zx44v
38m         Normal    SuccessfulDelete    replicaset/argocd-server-7698f7ddb4         Deleted pod: argocd-server-7698f7ddb4-zx44v
38m         Normal    SuccessfulCreate    replicaset/argocd-server-7698f7ddb4         Created pod: argocd-server-7698f7ddb4-v4x4m
38m         Normal    SuccessfulDelete    replicaset/argocd-server-7698f7ddb4         Deleted pod: argocd-server-7698f7ddb4-v4x4m
38m         Normal    SuccessfulCreate    replicaset/argocd-server-7698f7ddb4         Created pod: argocd-server-7698f7ddb4-rqr4x
38m         Normal    SuccessfulDelete    replicaset/argocd-server-7698f7ddb4         Deleted pod: argocd-server-7698f7ddb4-rqr4x
38m         Normal    SuccessfulCreate    replicaset/argocd-server-7698f7ddb4         Created pod: argocd-server-7698f7ddb4-75fbf
38m         Normal    SuccessfulDelete    replicaset/argocd-server-7698f7ddb4         Deleted pod: argocd-server-7698f7ddb4-75fbf
38m         Normal    SuccessfulCreate    replicaset/argocd-server-7698f7ddb4         Created pod: argocd-server-7698f7ddb4-rxlh6
38m         Normal    SuccessfulDelete    replicaset/argocd-server-7698f7ddb4         Deleted pod: argocd-server-7698f7ddb4-rxlh6
37m         Normal    SuccessfulCreate    replicaset/argocd-server-7698f7ddb4         Created pod: argocd-server-7698f7ddb4-6swwx
37m         Normal    SuccessfulDelete    replicaset/argocd-server-7698f7ddb4         Deleted pod: argocd-server-7698f7ddb4-6swwx
6m3s        Normal    SuccessfulCreate    replicaset/argocd-server-7698f7ddb4         Created pod: argocd-server-7698f7ddb4-9lcmt
5m43s       Normal    SuccessfulDelete    replicaset/argocd-server-7698f7ddb4         Deleted pod: argocd-server-7698f7ddb4-9lcmt
5m12s       Normal    SuccessfulCreate    replicaset/argocd-server-7698f7ddb4         Created pod: argocd-server-7698f7ddb4-rcx26
5m2s        Normal    SuccessfulDelete    replicaset/argocd-server-7698f7ddb4         Deleted pod: argocd-server-7698f7ddb4-rcx26
4m10s       Normal    SuccessfulCreate    replicaset/argocd-server-7698f7ddb4         Created pod: argocd-server-7698f7ddb4-ssq4v
4m5s        Normal    SuccessfulDelete    replicaset/argocd-server-7698f7ddb4         Deleted pod: argocd-server-7698f7ddb4-ssq4v
7m11s       Normal    ScalingReplicaSet   deployment/argocd-server                    Scaled up replica set argocd-server-6b6846dc74 to 1
7m21s       Normal    ScalingReplicaSet   deployment/argocd-server                    Scaled down replica set argocd-server-6b6846dc74 to 0
7m51s       Normal    ScalingReplicaSet   deployment/argocd-server                    Scaled up replica set argocd-server-69c56dd7c6 to 1
6m41s       Normal    ScalingReplicaSet   deployment/argocd-server                    Scaled down replica set argocd-server-69c56dd7c6 to 0
4m11s       Normal    ScalingReplicaSet   deployment/argocd-server                    Scaled up replica set argocd-server-7698f7ddb4 to 1
5m43s       Normal    ScalingReplicaSet   deployment/argocd-server                    Scaled down replica set argocd-server-7698f7ddb4 to 0
```

logs from the operator:
```
021-10-17T23:56:36.137Z        INFO    controller-runtime.manager.controller.argocd    Reconciling ArgoCD      {"reconciler group": "argoproj.io", "reconciler kind": "ArgoCD", "name": "argocd", "namespace": "jfr-argocd", "namespace": "jfr-argocd", "name": "argocd"}
2021-10-17T23:56:36.137Z        INFO    openshift_controller_argocd     configuring policy rule for Application Controller      {"ArgoCD Namespace": "jfr-argocd", "ArgoCD Name": "argocd"}
2021-10-17T23:56:36.164Z        INFO    openshift_controller_argocd     configuring policy rule for Application Controller      {"ArgoCD Namespace": "jfr-argocd", "ArgoCD Name": "argocd"}
2021-10-17T23:56:36.194Z        INFO    openshift_controller_argocd     configuring policy rule for Application Controller      {"ArgoCD Namespace": "jfr-argocd", "ArgoCD Name": "argocd"}
2021-10-17T23:56:36.460Z        INFO    openshift_controller_argocd     configuring policy rule for Redis HA    {"ArgoCD Namespace": "jfr-argocd", "ArgoCD Name": "argocd"}
2021-10-17T23:56:36.610Z        INFO    openshift_controller_argocd     configuring openshift cluster config policy rules       {"ArgoCD Namespace": "jfr-argocd", "ArgoCD Name": "argocd"}
2021-10-17T23:56:36.613Z        INFO    openshift_controller_argocd     configuring policy rule for Application Controller      {"ArgoCD Namespace": "jfr-argocd", "ArgoCD Name": "argocd"}
2021-10-17T23:56:36.663Z        INFO    openshift_controller_argocd     configuring policy rule for Application Controller      {"ArgoCD Namespace": "jfr-argocd", "ArgoCD Name": "argocd"}
2021-10-17T23:56:36.712Z        INFO    openshift_controller_argocd     configuring policy rule for Application Controller      {"ArgoCD Namespace": "jfr-argocd", "ArgoCD Name": "argocd"}
2021-10-17T23:56:36.932Z        INFO    openshift_controller_argocd     configuring policy rule for Redis HA    {"ArgoCD Namespace": "jfr-argocd", "ArgoCD Name": "argocd"}
2021-10-17T23:56:37.518Z        INFO    openshift_controller_argocd     configuring policy rule for Application Controller      {"ArgoCD Namespace": "jfr-argocd", "ArgoCD Name": "argocd"}
2021-10-17T23:56:37.571Z        INFO    openshift_controller_argocd     configuring policy rule for Application Controller      {"ArgoCD Namespace": "jfr-argocd", "ArgoCD Name": "argocd"}
2021-10-17T23:56:37.612Z        INFO    openshift_controller_argocd     configuring policy rule for Application Controller      {"ArgoCD Namespace": "jfr-argocd", "ArgoCD Name": "argocd"}
2021-10-17T23:56:37.673Z        INFO    openshift_controller_argocd     configuring policy rule for Redis HA    {"ArgoCD Namespace": "jfr-argocd", "ArgoCD Name": "argocd"}
2021-10-17T23:56:37.818Z        INFO    openshift_controller_argocd     configuring openshift cluster config policy rules       {"ArgoCD Namespace": "jfr-argocd", "ArgoCD Name": "argocd"}
2021-10-17T23:56:37.818Z        INFO    controller_argocd       URI: https://argocd-server-jfr-argocd.apps.os-global.finods.com/api/dex/callback
2021-10-17T23:56:37.891Z        INFO    openshift_controller_argocd     configuring openshift redis     {"ArgoCD Namespace": "jfr-argocd", "ArgoCD Name": "argocd"}
2021-10-17T23:56:42.168Z        INFO    controller-runtime.manager.controller.argocd    Reconciling ArgoCD      {"reconciler group": "argoproj.io", "reconciler kind": "ArgoCD", "name": "argocd", "namespace": "jfr-argocd", "namespace": "jfr-argocd", "name": "argocd"}
2021-10-17T23:56:42.179Z        INFO    controller_argocd_metrics       Reconciling ArgoCD Metrics      {"Request.Namespace": "jfr-argocd", "Request.Name": "argocd"}
2021-10-17T23:56:42.179Z        INFO    controller_argocd_metrics       Namespace already has cluster-monitoring label  {"Request.Namespace": "jfr-argocd", "Request.Name": "argocd", "Namespace": "jfr-argocd"}
2021-10-17T23:56:42.179Z        INFO    controller_argocd_metrics       Read role already exists        {"Request.Namespace": "jfr-argocd", "Request.Name": "argocd", "Namespace": "jfr-argocd", "Name": "jfr-argocd-read"}
2021-10-17T23:56:42.179Z        INFO    controller_argocd_metrics       Read role binding already exists        {"Request.Namespace": "jfr-argocd", "Request.Name": "argocd", "Namespace": "jfr-argocd", "Name": "jfr-argocd-prometheus-k8s-read-binding"}
2021-10-17T23:56:42.179Z        INFO    controller_argocd_metrics       A ServiceMonitor instance already exists        {"Request.Namespace": "jfr-argocd", "Request.Name": "argocd", "Namespace": "jfr-argocd", "Name": "argocd"}
2021-10-17T23:56:42.179Z        INFO    controller_argocd_metrics       A ServiceMonitor instance already exists        {"Request.Namespace": "jfr-argocd", "Request.Name": "argocd", "Namespace": "jfr-argocd", "Name": "argocd-server"}
2021-10-17T23:56:42.179Z        INFO    controller_argocd_metrics       A ServiceMonitor instance already exists        {"Request.Namespace": "jfr-argocd", "Request.Name": "argocd", "Namespace": "jfr-argocd", "Name": "argocd-repo-server"}
2021-10-17T23:56:42.179Z        INFO    controller_argocd_metrics       An alert rule instance already exists   {"Request.Namespace": "jfr-argocd", "Request.Name": "argocd", "Namespace": "jfr-argocd", "Name": "gitops-operator-argocd-alerts"}
2021-10-17T23:56:42.192Z        INFO    controller_argocd_metrics       Reconciling ArgoCD Metrics      {"Request.Namespace": "jfr-argocd", "Request.Name": "argocd"}
2021-10-17T23:56:42.192Z        INFO    controller_argocd_metrics       Namespace already has cluster-monitoring label  {"Request.Namespace": "jfr-argocd", "Request.Name": "argocd", "Namespace": "jfr-argocd"}
2021-10-17T23:56:42.192Z        INFO    controller_argocd_metrics       Read role already exists        {"Request.Namespace": "jfr-argocd", "Request.Name": "argocd", "Namespace": "jfr-argocd", "Name": "jfr-argocd-read"}
2021-10-17T23:56:42.192Z        INFO    controller_argocd_metrics       Read role binding already exists        {"Request.Namespace": "jfr-argocd", "Request.Name": "argocd", "Namespace": "jfr-argocd", "Name": "jfr-argocd-prometheus-k8s-read-binding"}
2021-10-17T23:56:42.192Z        INFO    controller_argocd_metrics       A ServiceMonitor instance already exists        {"Request.Namespace": "jfr-argocd", "Request.Name": "argocd", "Namespace": "jfr-argocd", "Name": "argocd"}
2021-10-17T23:56:42.192Z        INFO    controller_argocd_metrics       A ServiceMonitor instance already exists        {"Request.Namespace": "jfr-argocd", "Request.Name": "argocd", "Namespace": "jfr-argocd", "Name": "argocd-server"}
2021-10-17T23:56:42.192Z        INFO    controller_argocd_metrics       A ServiceMonitor instance already exists        {"Request.Namespace": "jfr-argocd", "Request.Name": "argocd", "Namespace": "jfr-argocd", "Name": "argocd-repo-server"}
2021-10-17T23:56:42.192Z        INFO    controller_argocd_metrics       An alert rule instance already exists   {"Request.Namespace": "jfr-argocd", "Request.Name": "argocd", "Namespace": "jfr-argocd", "Name": "gitops-operator-argocd-alerts"}
2021-10-17T23:56:42.194Z        INFO    openshift_controller_argocd     configuring policy rule for Application Controller      {"ArgoCD Namespace": "jfr-argocd", "ArgoCD Name": "argocd"}
2021-10-17T23:56:42.213Z        INFO    openshift_controller_argocd     configuring policy rule for Application Controller      {"ArgoCD Namespace": "jfr-argocd", "ArgoCD Name": "argocd"}
2021-10-17T23:56:42.233Z        INFO    openshift_controller_argocd     configuring policy rule for Application Controller      {"ArgoCD Namespace": "jfr-argocd", "ArgoCD Name": "argocd"}
2021-10-17T23:56:42.468Z        INFO    openshift_controller_argocd     configuring policy rule for Redis HA    {"ArgoCD Namespace": "jfr-argocd", "ArgoCD Name": "argocd"}
2021-10-17T23:56:42.620Z        INFO    openshift_controller_argocd     configuring openshift cluster config policy rules       {"ArgoCD Namespace": "jfr-argocd", "ArgoCD Name": "argocd"}
2021-10-17T23:56:42.620Z        INFO    openshift_controller_argocd     configuring policy rule for Application Controller      {"ArgoCD Namespace": "jfr-argocd", "ArgoCD Name": "argocd"}
2021-10-17T23:56:42.664Z        INFO    openshift_controller_argocd     configuring policy rule for Application Controller      {"ArgoCD Namespace": "jfr-argocd", "ArgoCD Name": "argocd"}
2021-10-17T23:56:42.716Z        INFO    openshift_controller_argocd     configuring policy rule for Application Controller      {"ArgoCD Namespace": "jfr-argocd", "ArgoCD Name": "argocd"}
2021-10-17T23:56:42.923Z        INFO    openshift_controller_argocd     configuring policy rule for Redis HA    {"ArgoCD Namespace": "jfr-argocd", "ArgoCD Name": "argocd"}
2021-10-17T23:56:43.518Z        INFO    openshift_controller_argocd     configuring policy rule for Application Controller      {"ArgoCD Namespace": "jfr-argocd", "ArgoCD Name": "argocd"}
2021-10-17T23:56:43.562Z        INFO    openshift_controller_argocd     configuring policy rule for Application Controller      {"ArgoCD Namespace": "jfr-argocd", "ArgoCD Name": "argocd"}
2021-10-17T23:56:43.613Z        INFO    openshift_controller_argocd     configuring policy rule for Application Controller      {"ArgoCD Namespace": "jfr-argocd", "ArgoCD Name": "argocd"}
2021-10-17T23:56:43.679Z        INFO    openshift_controller_argocd     configuring policy rule for Redis HA    {"ArgoCD Namespace": "jfr-argocd", "ArgoCD Name": "argocd"}
2021-10-17T23:56:43.822Z        INFO    openshift_controller_argocd     configuring openshift cluster config policy rules       {"ArgoCD Namespace": "jfr-argocd", "ArgoCD Name": "argocd"}
2021-10-17T23:56:43.822Z        INFO    controller_argocd       URI: https://argocd-server-jfr-argocd.apps.os-global.finods.com/api/dex/callback
2021-10-17T23:56:43.895Z        INFO    openshift_controller_argocd     configuring openshift redis     {"ArgoCD Namespace": "jfr-argocd", "ArgoCD Name": "argocd"}
2021-10-17T23:56:48.143Z        INFO    controller-runtime.manager.controller.argocd    Reconciling ArgoCD      {"reconciler group": "argoproj.io", "reconciler kind": "ArgoCD", "name": "argocd", "namespace": "jfr-argocd", "namespace": "jfr-argocd", "name": "argocd"}
2021-10-17T23:56:48.143Z        INFO    openshift_controller_argocd     configuring policy rule for Application Controller      {"ArgoCD Namespace": "jfr-argocd", "ArgoCD Name": "argocd"}
2021-10-17T23:56:48.165Z        INFO    openshift_controller_argocd     configuring policy rule for Application Controller      {"ArgoCD Namespace": "jfr-argocd", "ArgoCD Name": "argocd"}
2021-10-17T23:56:48.179Z        INFO    openshift_controller_argocd     configuring policy rule for Application Controller      {"ArgoCD Namespace": "jfr-argocd", "ArgoCD Name": "argocd"}
2021-10-17T23:56:48.462Z        INFO    openshift_controller_argocd     configuring policy rule for Redis HA    {"ArgoCD Namespace": "jfr-argocd", "ArgoCD Name": "argocd"}
2021-10-17T23:56:48.607Z        INFO    openshift_controller_argocd     configuring openshift cluster config policy rules       {"ArgoCD Namespace": "jfr-argocd", "ArgoCD Name": "argocd"}
2021-10-17T23:56:48.607Z        INFO    openshift_controller_argocd     configuring policy rule for Application Controller      {"ArgoCD Namespace": "jfr-argocd", "ArgoCD Name": "argocd"}
2021-10-17T23:56:48.662Z        INFO    openshift_controller_argocd     configuring policy rule for Application Controller      {"ArgoCD Namespace": "jfr-argocd", "ArgoCD Name": "argocd"}
2021-10-17T23:56:48.712Z        INFO    openshift_controller_argocd     configuring policy rule for Application Controller      {"ArgoCD Namespace": "jfr-argocd", "ArgoCD Name": "argocd"}
2021-10-17T23:56:48.926Z        INFO    openshift_controller_argocd     configuring policy rule for Redis HA    {"ArgoCD Namespace": "jfr-argocd", "ArgoCD Name": "argocd"}
2021-10-17T23:56:49.518Z        INFO    openshift_controller_argocd     configuring policy rule for Application Controller      {"ArgoCD Namespace": "jfr-argocd", "ArgoCD Name": "argocd"}
2021-10-17T23:56:49.566Z        INFO    openshift_controller_argocd     configuring policy rule for Application Controller      {"ArgoCD Namespace": "jfr-argocd", "ArgoCD Name": "argocd"}
2021-10-17T23:56:49.613Z        INFO    openshift_controller_argocd     configuring policy rule for Application Controller      {"ArgoCD Namespace": "jfr-argocd", "ArgoCD Name": "argocd"}
2021-10-17T23:56:49.688Z        INFO    openshift_controller_argocd     configuring policy rule for Redis HA    {"ArgoCD Namespace": "jfr-argocd", "ArgoCD Name": "argocd"}
2021-10-17T23:56:49.826Z        INFO    openshift_controller_argocd     configuring openshift cluster config policy rules       {"ArgoCD Namespace": "jfr-argocd", "ArgoCD Name": "argocd"}
2021-10-17T23:56:49.827Z        INFO    controller_argocd       URI: https://argocd-server-jfr-argocd.apps.os-global.finods.com/api/dex/callback
2021-10-17T23:56:49.914Z        INFO    openshift_controller_argocd     configuring openshift redis     {"ArgoCD Namespace": "jfr-argocd", "ArgoCD Name": "argocd"}
```

**To Reproduce**
Upgrade from 1.2.x to 1.3.0

**Expected behavior**
Should reach a stable state

**Screenshots**

**Additional context**

**Comment by iam-veeramalla** [comment] 2021-10-20 17:51
I will work on this

**Comment by iam-veeramalla** [comment] 2021-10-21 08:55
> ssh-known-hosts"

I upgraded the operator to v1.3.0 from `v1.2.1 and v1.2.0`. In both the cases, I dont see any issue with the `ssh-known-hosts` volume.

Any of you seeing the same event w.r.t `ssh-known-hosts` @arjunprasad2143 @davidkarlsen

**Comment by iam-veeramalla** [comment] 2021-10-21 09:30
> cannot find volume "ssh-known-hosts" to mount into container "argocd-server"

Thanks @arjunprasad2143 for the information.

**Comment by wtam2018** [comment] 2021-10-22 04:13
There is a report of repo server crashing issue.  https://github.com/argoproj/argo-cd/issues/7484.   Are you guys syncing helm charts?  @davidkarlsen @arjunprasad2143 @EagleIJoe

**Comment by mgruener** [comment] 2021-11-01 07:33
The ArgoCD instance has remained stable over the weekend, no pod recreations. From my point of view the problem is fixed.

**Comment by EagleIJoe** [comment] 2021-11-01 21:29
Had no issues whatsoever after the update to 1.3.1. I propose closing the issue.

**Comment by arjunprasad2143** [comment] 2021-11-02 14:00
No issues. Can be closed

**Comment by EagleIJoe** [comment] 2021-11-06 20:05
@davidkarlsen i think you can safely close this. The errata has been published as well...

**Closed** 2021-11-06 20:18 UTC
Labels: kind/bug
